### ISSUE TITLE
Show buttons in file view

### ISSUE THREAD

**Issue by lonix1** [AnWeber/vscode-gitbuttons#1]
Thanks for this interesting new extension!

I was wondering whether it's possible to show the buttons in the file view (above the opened file)? So if a file with changes is open, I can click e.g. the "add" button to perform a `git add <file>`.

That is even more useful, because we spend most of our time in the file view, and only some of the time in the source control view.

**Comment by AnWeber** [comment]
I have now added the display of the buttons in the title of workbench.explorer.fileView. But unfortunately I cannot offer to automatically add the currently selected file in the explorer with command `git-buttons.stage` (instead, the currently active file is used, [see](https://github.com/microsoft/vscode/blob/main/extensions/git/src/commands.ts#L815-L822) and [line 2872](https://github.com/microsoft/vscode/blob/main/extensions/git/src/commands.ts#L2872)). The request has already been recorded at [VSCode (microsoft/vscode#3553)](https://github.com/microsoft/vscode/issues/3553), but is currently not yet implemented.

**Comment by lonix1** [comment]
Thanks that's a nice workaround until the vscode API allows for more. :smiley: I upvoted that feature request.

**Comment by AnWeber** [comment]
Thanks, no workaround from me. Default behaviour of vscode git extension.
