### ISSUE TITLE
Reaching out

### ISSUE THREAD

**Issue by yashpalgoyal1304** [AnWeber/vscode-gitbuttons#2]
Hi!
Congratulations of getting ur extension [published]. And thanks a lot for publishing it on open-vsx as well [anweber.git-buttons]
Have a nice day!

[published]: https://code.visualstudio.com/updates/v1_62#_web-extensions
[anweber.git-buttons]: https://open-vsx.org/vscode/item?itemName=anweber.git-buttons

**Comment by AnWeber** [comment]
Thx:-)
